name: Metrics
on:
  schedule:
    - cron: "14 2 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: frieren-mage/metrics@master
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories,
          base_hireable: yes

      - name: Achievements
        uses: frieren-mage/metrics@master
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, deployer, member, maintainer, developer,
            scripter
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X

      - name: Language Metrics
        uses: frieren-mage/metrics@master
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          commits_authoring: jared, jared koontz, koontz, jaredkoontz, jaredkoontz@users.noreply.github.com
          plugin_languages_ignored: >-
            html, css, jinja, tex, less, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 50
          plugin_languages_categories: data,markup,programming,prose
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 100

