name: Metrics
on:
  schedule:
    - cron: "14 2 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories,
          base_hireable: yes
#
#      - name: Achievements
#        uses: lowlighter/metrics@latest
#        with:
#          filename: metrics.plugin.achievements.compact.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          base: ""
#          plugin_achievements: yes
#          plugin_achievements_only: >-
#            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
#            scripter, packager, explorer, infographile, manager
#          plugin_achievements_display: compact
#          plugin_achievements_threshold: X

      - name: Language Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          commits_authoring: jared, jared koontz, koontz, jaredkoontz, jaredkoontz@users.noreply.github.com
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, jinja, conf, apacheconf, svg, scss, json, markdown, md, text, txt,
            yaml, yml, xml, toml, ini, robots.txt
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_details: lines
          plugin_languages_indepth: yes
#          plugin_languages_other: yes
          plugin_languages_analysis_timeout: 50
          plugin_languages_categories: markup,programming
#          plugin_languages_categories: data, prose
#          plugin_languages_recent_categories: data, prose
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

